### ISSUE TITLE
Getting Please provide a valid path to your results file with the -f argument.

### ISSUE THREAD

**Issue by Mayur-Suryawanshi1992** [gurock/trcli-action#2]
Always get an error "Getting Please provide a valid path to your results file with the -f argument."
![gitaction0](https://github.com/gurock/trcli-action/assets/46771677/ea6f4fd9-b9ff-43a3-a8c2-f116ed94554b)
![gitaction1](https://github.com/gurock/trcli-action/assets/46771677/0bbb9ccc-0cfa-4f0f-91ed-f67ccd8dea2a)

**Comment by Mayur-Suryawanshi1992** [comment]
Trying to integrate PROVAR generated Test result with TestRail.

**Comment by bitcoder** [comment]
1. Can you please try using ' instead of " as a delimeter for the report_file_path configuration?
2. From the screenshot, it was not clear if the command actually succeeded or not? Did it push the results? or did it aborted the CLI command?

**Comment by bitcoder** [comment]
I think you may have a typo in the report path.. you have TestRailGitIntegration twice: `/home/runner/work/TestRailGitIntegration/TestRailGitIntegration/TESTs-TestSuites.xml`

My suggestion would be to add an additional step before the cli one, and make a "ls -la ...." to see if the file exists on the path that you specified. 
It doesn't seem to be a problem with this GH action at this point
